### ISSUE TITLE
Use CSS LEDs

### ISSUE THREAD

**Issue by rralf** [Binary-Kitchen/doorlockd#7]
Switch to shinier CSS LEDs.

**Comment by rralf** [comment]
Xaver, any updates on this? Didn't you want to implement css-based LEDs?

**Comment by rralf** [comment]
Ok, I guess that's a no ;-)

**Comment by xf-** [comment]
no time and i think the stuff changed a lot. i cleaned up some github stuff

**Comment by rralf** [comment]
Fair enough. Let's keep this issue closed.

**Comment by xf-** [comment]
you can switch the assignee or we can take a look at UI someday
